spring.application.name=ms-proyectos
# PUERTO CORRECTO PARA PROYECTOS (Para que no choque con el 8080 o 8081)
server.port=8082

# Configuración de Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/proyectos_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Evitar conflicto de puerto si algo quedó abierto
server.error.include-message=always

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer